version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -e .
  pre_build:
    commands:
      - echo "Started test case execution!!"
      - find . -name "*.py" -exec pylint '{}' \;
      - cd flaskerino && python tests/test_index.py -v
  post_build:
    commands:
      - echo "After executing test cases"
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo "Printed CODE_BUILD_SUCCEEDING"
      - echo CODEBUILD_SOURCE_REPO_URL:$CODEBUILD_SOURCE_REPO_URL CODEBUILD_SOURCE_VERSION:$CODEBUILD_SOURCE_VERSION CODEBUILD_WEBHOOK_TRIGGER:$CODEBUILD_WEBHOOK_TRIGGER > CODE_BUILD_DATA
artifacts:
  files:
    - '**/*'
  discard-paths: no
