version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -e .
  pre_build:
    commands:
      - find . -name "*.py" -exec pylint '{}' \;
      - cd flaskerino && python tests/test_index.py -v
  post_build:
    commands:
      - find . -name "*.py" -exec pylint '{}' \;
      - python tests/test_dummy.py -v
artifacts:
  files:
    - '**/*'
  discard-paths: no
